# filter_features:
#   filter_settings: 
#     compute_diptest:            Compute Hartigan's dip test
#     compute_entropy:            Compute entropy of the features
#     compute_std:                Compute standard deviation of the features
#     diptest_significance_level: Significance level for the dip test (0 to skip filter, reduce to filter out more features)
#     entropy_quantile:           Entropy quantile to use for filtering (0 to skip filter, reduce to filter out more features)
#     std_quantile:               Standard deviation quantile to use for filtering (0 to skip filter, reduce to filter out more features)

filter_settings:
  compute_diptest: True              
  compute_entropy: True              
  compute_std: True                  
  diptest_significance_level: 0.05   
  entropy_quantile: 0                
  std_quantile: 0                   