
compute_features:
  plumed_settings:
    traj_stride: 1
    features:
      distance_groups:
        L1_relative_position: 
          first_selection: "not name H*"
          second_selection: "not name H*"
          first_stride: 1
          second_stride: 2
          skip_neigh_residues: False
          skip_bonded_atoms: True

filter_features:
    filter_settings:
        compute_diptest: True              
        compute_entropy: True             
        compute_std: True                
        diptest_significance_level: 0.05   
        entropy_quantile: 0                
        std_quantile: 0                           
    sampling_settings:
        relaxation_time: 1  
        
train_colvars:
  cvs: ['pca', 'ae', 'tica', 'deep_tica']
  common:
    dimension: 2
    input_colvars: 
      start: 0
      stop: null
      stride: 1 
    architecture:
      hidden_layers: [5, 3]
      lag_time: 1                        
      pca_lowrank_q: null
    training: 
      general:
        max_tries: 3
        seed: 42
        lengths: [0.8, 0.2]
        batch_size: 256
        max_epochs: 1000
        dropout: 0.1
        shuffle: False
        random_split: True
        check_val_every_n_epoch: 1
        save_check_every_n_epoch: 1
      early_stopping:
        patience: 20
        min_delta: 1.0e-05
      optimizer:
        name: Adam
        kwargs: 
          lr: 1.0e-02 
          weight_decay: 0
      save_loss: True
      plot_loss: True
  ae:           
    training:
      early_stopping:
        patience: 100
      optimizer:
        kwargs: 
          lr: 1.0e-04
  figures:
    fes:
      compute: True  
      save: True  
      temperature: 300
      bandwidth: 0.025
      num_bins: 200
      num_blocks: 1
      max_fes: 18
    traj_projection:
      plot: True
      num_bins: 100
      bandwidth: 0.25
      alpha: 0.6
      cmap: turbo
      use_legend: True
      marker_size: 12
  clustering:                        
    run: True                        
    algorithm: hierarchical               
    opt_num_clusters: True          
    search_interval: [3, 4]          
    num_clusters: 3                  
    linkage: complete                
    n_init: 20                       
    min_cluster_size: 50             
    min_samples: 5                  
    cluster_selection_epsilon: 0